### PR TITLE
Test page WIP, for #3

### PR DESCRIPTION
**Pull request by timdream**
Unfortnately this does not work yet.

* EmojiOne does not render on canvas -- I can't read it's pixels
* SVG image does not render on canvas -- I can't read the reference pixels

### CODE REVIEW

**Comment by timdream** [comment]
screen shot 2016-05-23 at 18 14 54

@jfkthame Sadly, w/o fixing the canvas rendering, I can already see HTML font rendering defect on Ubuntu (but not on Windows).

**Comment by timdream** [comment]
@jfkthame Would it be possible that empty SVG already the bug filed as https://bugzilla.mozilla.org/show_bug.cgi?id=700533#c18 ?

**Comment by timdream** [comment]
> @jfkthame Would it be possible that empty SVG already the bug filed as https://bugzilla.mozilla.org/show_bug.cgi?id=700533#c18 ?

Look like it, will need a workaround...

**Comment by jfkthame** [comment]
The ubuntu vs mac difference is interesting... I suspect the rasterizers must be using different fill rules.

FWIW, there are a few glyphs where I see problems on Mac, too, when viewing http://people.mozilla.org/~jkew/tests/emoji-list.html ... see rows 1330 and following in the table there. This seems to be related to how the original SVG paths are constructed, and we may need to tweak them to work around it.

**Comment by timdream** [comment]
> The ubuntu vs mac difference is interesting... I suspect the rasterizers must be using different fill rules, or perhaps treating unclosed paths differently.

This means we can't ship the font (w/ bug 1270418) unless this test page is constructed and tests passes on the 3 targets: Linux, Windows (GDI), and Windows 8 (DWrite).

**Comment by timdream** [comment]
The test page is complete. It now asserts the following:

1. SVG source rendering must not be empty (```reference```)
2. EmojiOne rendering must not be empty (```rendering```)
3. EmojiOne rendering must be different than system font rendering (```webfont```)
4. EmojiOne rendering must match SVG source rendering (```mismatch```)

All 1640 items takes about ~7 min to run. Which is a little sad. I can see one false negative (U+2747 & U+2744 cause their complex border lines), but for some pixel diff ~ 1% images we are indeed missing small details.

There are 340 items with > 1% pixel differences. It would take some time to go through all of them ...

If we all agree this test page is the right target to work on, I will merge this branch tomorrow.

**Comment by mikedeboer** [comment]
My bet is on resemble.js being slow... which wouldn't surprise me.
Of course, it'd be way faster to do comparisons in a NodeJS script using an ImageMagik wrapper.

**Comment by jfkthame** [comment]
Looking at the discrepancies here, I think there are a few types of problems that we can try to address:
(1) I see some color mismatches that I suspect may be due to non-100% opacity being lost in the conversion. I have just pushed a fix that should help with some of these.
(2) Paths in the SVG that are stroked (rather than filled) are not converted properly. Looks like the svg-to-ttf tool doesn't support that, so we may need to pre-process the SVGs to expand paths (perhaps scriptable through inkscape?)
(3) There are some cases where the SVG has a single path that results in several disjoint filled areas, presumably through use of self-intersecting paths and even-odd fill or stuff like that; we may need to simplify these (inkscape's "break apart" operation?)

**Comment by jfkthame** [comment]
Aside from the time it takes to run (which we can live with if necessary), this is very cool.

A couple of enhancements that I'd appreciate:
- the ability to re-collapse row after it's been clicked to display the result; currently this is a one-way operation, but I'd like to be able to toggle the result visibility
- annotate the results with character names (as in the Name column of http://people.mozilla.org/~jkew/tests/emoji-list.html, though lowercased would be nicer), for searchability

Neither of these are critical, obviously, but I'd find them handy.

**Comment by timdream** [comment]
@jfkthame I'll do that what you suggested after merging this to master (so I can see your new pushes). Thanks!

**Pull request merged**
